services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "AccessHub_Strong_Pass123!"
    ports:
      - "1433:1433"
    volumes:
      - accesshub-sql:/var/opt/mssql

volumes:
  accesshub-sql:
